ATAK Module
LDAPAccountManager/lam pull request #362
Opened 2024-09-23 11:51 UTC by miniwg

Provide ATAK user management module

2024-09-23 14:53 UTC, gruberroland requested changes

2024-09-23 14:53 UTC, gruberroland commented on lam/graphics/TakLogo.png
please use tak.png which is already on develop branch

2024-09-23 14:53 UTC, gruberroland commented on .DS_Store
no .DS_Store files please :)

2024-09-24 11:10 UTC, miniwg commented on lam/graphics/TakLogo.png
Removed

2024-09-24 11:10 UTC, miniwg commented on .DS_Store
Oops removed

2025-03-20 20:27 UTC, gruberroland requested changes

2025-03-20 20:27 UTC, gruberroland commented on lam/lib/modules/takUser.inc
> +	const DATE_REGEX = '/^([\d]{1,2})\\.([\d]{1,2})\\.([\d]{4})( ([\d]{1,2}):([\d]{1,2}))?$/';
Looks like this can be removed

2025-03-20 20:27 UTC, gruberroland commented on lam/lib/modules/takUser.inc
> +		$return['attributes'] = ['takCallsign', 'takRole', 'takColor'
please put all attribute names in lower-case (e.g. "takcallsign"). Same everywhere where you access this->attributes/orig. The background is that we get everything lower-case from LDAP and want to get rid of our workaround to restore the camel-case names.

2025-03-20 20:27 UTC, gruberroland commented on lam/lib/modules/takUser.inc
> +		* not working: will not allow -
I guess you will need to implement check_profileOptions() for the checks

2025-03-20 20:27 UTC, gruberroland commented on lam/lib/modules/takUser.inc
> +		$return->add(new htmlResponsiveSelect('takRole', ['Team Member', 'Team Leader', 'HQ', 'Sniper', 'Medic', 'Forward Observer', 'RTO', 'K9'], ['Team Member'], _('TAK team role'), 'takRole'), 12);
Please define the possible roles+colors in one central place (and use it for e.g. file upload, too).

2025-03-20 20:27 UTC, gruberroland commented on lam/lib/modules/takUser.inc
> +			$this->attributes['takCallsign'] = explode(',', $profile['takUser_takCallsign'][0]);
no need for "explode" for all attributes (as they are single-valued)

2025-03-20 20:27 UTC, gruberroland commented on lam/lib/modules/takUser.inc
> +			$partialAccounts[$i]['takCallsign'] = $rawAccounts[$i][$ids['takUser_takCallsign']];
please add a check for color/role

2025-03-20 20:28 UTC, gruberroland commented on lam/lib/modules/takUser.inc
> +  Copyright (C) 2010 - 2024  Roland Gruber
Please use the same header comment as e.g. inetOrgPerson.inc (with your name)

2025-03-21 14:28 UTC, miniwg commented on lam/lib/modules/takUser.inc
> +	const DATE_REGEX = '/^([\d]{1,2})\\.([\d]{1,2})\\.([\d]{4})( ([\d]{1,2}):([\d]{1,2}))?$/';
Removed

2025-03-21 14:29 UTC, miniwg commented on lam/lib/modules/takUser.inc
> +		$return->add(new htmlResponsiveSelect('takRole', ['Team Member', 'Team Leader', 'HQ', 'Sniper', 'Medic', 'Forward Observer', 'RTO', 'K9'], ['Team Member'], _('TAK team role'), 'takRole'), 12);
Created new private arrays for roles & colours

2025-03-21 14:32 UTC, miniwg commented on lam/lib/modules/takUser.inc
> +			$this->attributes['takCallsign'] = explode(',', $profile['takUser_takCallsign'][0]);
Removed explodes

2025-03-21 14:33 UTC, miniwg commented on lam/lib/modules/takUser.inc
> +			$partialAccounts[$i]['takCallsign'] = $rawAccounts[$i][$ids['takUser_takCallsign']];
I need some help with that

2025-03-21 14:33 UTC, miniwg commented on lam/lib/modules/takUser.inc
> +  Copyright (C) 2010 - 2024  Roland Gruber
Changed header to same style

2025-03-21 14:34 UTC, miniwg commented on lam/lib/modules/takUser.inc
> +		$return['attributes'] = ['takCallsign', 'takRole', 'takColor'
All entity names changed to lower case

2025-03-27 18:48 UTC, gruberroland approved these changes

2025-03-27 18:54 UTC, merged