major correction of mistakes in the French translation
LDAPAccountManager/lam pull request #49
Opened 2018-05-11 02:55 UTC by etlel

I corrected a lot of mistakes and inconsistencies in the French translation files. It may not be perfect at this stage but it is far more better than previously. I am pleased to see this contribution integrated as soon as possible.

Regards,

2018-05-12 13:10 UTC, gruberroland requested changes
Merci beaucoup! I found some potential issues using my little French knowledge from school.
Please recheck them if any changes are required.

Anyway, looks like you solved a lot of issues. Thanks a lot for your work. :)

2018-05-12 13:10 UTC, gruberroland commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +msgstr "Ajouter l'extension Adresse IP"
Can you recheck this one? E.g. here it is as it was before: https://fr.wikipedia.org/wiki/Adresse_IP

2018-05-12 13:10 UTC, gruberroland commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +msgstr "Ajouter l'extensions de boîte vocale Asterisk"
Should be "l'extension" (singular)?

2018-05-12 13:10 UTC, gruberroland commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +"Numéros de comptes affichés commencent à \"0\". Ajouter 2 pour obtenir la "
Please recheck if this should be Ajoute/Ajoutez.

2018-05-12 13:10 UTC, gruberroland commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +msgstr "Entrée créée"
Is the third e correct?

2018-05-12 13:10 UTC, gruberroland commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +"Nom de la machine qui doit être créée. Les caractères autorisés sont : a-z,A-"
Please recheck the third e in créée.

2018-05-12 13:10 UTC, gruberroland commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +msgstr "LAM n'a pu trouver de domaine portant ce nom!"
Please recheck "pu trouver"

2018-05-12 13:10 UTC, gruberroland commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +msgstr "Paramètres de lamdaemon"
**L**amdaemon?

2018-05-12 13:10 UTC, gruberroland commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +msgstr "version de Lamdaemon"
Should be "**V**ersion"?

2018-05-12 13:10 UTC, gruberroland commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +msgstr "Courrier"
Should stay "Courier" as it is the name of a software.

2018-05-12 15:57 UTC, etlel commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +msgstr "Ajouter l'extension Adresse IP"
As it is the extension "name". But another version could be "Ajouter l'extension d'adresse IP" and that would indeed be consistent with other related messages.

2018-05-12 15:58 UTC, etlel commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +msgstr "Ajouter l'extensions de boîte vocale Asterisk"
I changed all these mentions of specific extensions to singular. Forgot half of this one.

2018-05-12 16:00 UTC, etlel commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +msgstr "Entrée créée"
Yes it is right :) https://fr.wiktionary.org/wiki/cr%C3%A9%C3%A9e

2018-05-12 16:02 UTC, etlel commented on lam/locale/fr_FR/LC_MESSAGES/messages.po
> +msgstr "LAM n'a pu trouver de domaine portant ce nom!"
"n'a pas trouvé" = didn't find; "n'a (pas) pu trouver"= "couldn't find". I changed some messages for consistency reasons.

2018-05-12 17:14 UTC, etlel commented
Before merging, I'd like to review the translations related to "block". I have been confused by the potential multiple meanings that seems to being used. For instance, I believe that one is [block](https://en.wikipedia.org/wiki/Block_(data_storage)) (in "Block soft quota"; _bloc_ in French). But also [blocking](https://en.wikipedia.org/wiki/Wikipedia:Blocking_policy) (in "Grace block period"; _blocage_ in French). So I need more context around less precise strings like "Hard inode" or "Hard inode limit" to be sure that _hard_ is about the limit or the inode... and so on for "Hard block", "Hard block limit"...

2018-05-13 18:04 UTC, gruberroland commented
In this context, block is a block in the file system. So not related to blocking. Also in grace block period it is about a file system block.
In "Hard inode (limit)" the hard is about the limit. There is a soft and a hard limit. Same for hard block (limit).
Please let me know if you need more details.

2018-05-29 15:58 UTC, gruberroland commented
@etlel Can you update the pull request or do you need any additional information?

2018-06-03 15:50 UTC, gruberroland commented
Thanks a lot for your update! :)

2018-06-03 15:50 UTC, merged